language: python
python:
- '3.6'
env:
  global:
  - MEERKAT_AUTH_SETTINGS="${TRAVIS_BUILD_DIR}/meerkat_libs/meerkat_libs/auth_client/dev_auth_config.py"
  - CONFIG_OBJECT="config.Testing"
addons:
  postgresql: '9.6'
services:
- postgresql
install:
- pip install .
- pip install -r requirements.txt
- cd ..
- git clone --branch development --single-branch https://github.com/meerkat-code/meerkat_libs.git
- pip install -r meerkat_libs/requirements.txt
- export PYTHONPATH=$PYTHONPATH:$HOME/build/meerkat-code/meerkat_libs/
- cd meerkat_logging/
script: nosetests --logging-level=WARNING
notifications:
  slack:
    secure: JZq7ArBfLKEGSeFMA2pM5LYqWddlS96QHnu4+Z5qD5g2eiyXFjFw/k0cF5VKCKi9OfWMpJUQmy7Ic6iouFpXfxUC8x/TToOmn5oAxIouzU/vfth/vft0TY7+zksgbIzDPsFZDtbEJGyZBsSy3KMk0s6D61l91skuoSu9owS3a4gpKQyaonEQJr38yP6wPe5OWMlGO4hcUIjjvxjcXH/JwHOUobqxs4qOS/3/WfVjjhLunPdVE1e3Sv4Ws+Mnix3ZQXlUnadSfElFcQCB+dAq75ip4ls/CD+5PC9xQ7KFosoEJ0iWV0Z5ASYEXhupoDwHgyYquMoOyFkDsySHM6rByzey6vypfXad4pBV0tubPDluGFxkSC47F9H2Dpbla/zPOkOM8UnuOLiwE9vPzyEE3JWjeniHqJlTIViVEed+m/YK+FBvfUt64+0NjPvrma+n83V9Wa6wAYkesMnCcr/x6QOnZ+trfT5hq6lxGOT8kKTDu5pV3/QSxnsrHv2IMua56ptKWZr2eiGaXcmbuLKiTmaLZoT65HIEqgMLPduUoawo9ocoZEB7Up1lYfDXssgPDwZr6qR7u2RGvK8b4sq4JkfiWkgsQ84NOncJ7tYCaJ0dz1HNXDXyj7w5sB7laiX6ZU7Ga+PtwGqy7+/SPC4ybRmhSNwPHGoxQaoRDSDDvvg=
